FROM alpine:latest
LABEL version="3.15.0" maintainer="LAFDI Brahim" os="ubuntu"
ENV CONTAINER_USER="LAFDI"
RUN mkdir CONTAINER_USER
CMD ”hello-alpine, I’m CONTAINER_USER and this is a container from my first image”
